apiVersion: v1
kind: Service
metadata:
  name: vue-production-svc
  namespace: product
spec:
  type: NodePort
  selector:
    app: vue-production
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
