version: "3.8"

services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=post_db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 5050:80
    depends_on:
      - db
  app:
    container_name: facility_backend
    image: hul0810/fastapi_backend:0.0
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always